// <auto-generated />
using System;
using MaquinaDeTroco.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaquinaDeTroco.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201010004342_IniciandoModelagem")]
    partial class IniciandoModelagem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaquinaDeTroco.Models.Caixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Caixas");
                });

            modelBuilder.Entity("MaquinaDeTroco.Models.Moeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("SaldoId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SaldoId");

                    b.ToTable("Moeda");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Um centavo",
                            Valor = 0.10000000000000001
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Cinco centavos",
                            Valor = 0.5
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Dez centavos",
                            Valor = 0.10000000000000001
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Vinte e Cinco centavos",
                            Valor = 0.25
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Cinquenta centavos",
                            Valor = 0.5
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Um real",
                            Valor = 1.0
                        });
                });

            modelBuilder.Entity("MaquinaDeTroco.Models.Saldo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaixaId")
                        .HasColumnType("int");

                    b.Property<int>("MoedaId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaixaId");

                    b.ToTable("Saldos");
                });

            modelBuilder.Entity("MaquinaDeTroco.Models.Sangria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaixaId")
                        .HasColumnType("int");

                    b.Property<int>("MoedaId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaixaId");

                    b.HasIndex("MoedaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sangrias");
                });

            modelBuilder.Entity("MaquinaDeTroco.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Senha")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MaquinaDeTroco.Models.Moeda", b =>
                {
                    b.HasOne("MaquinaDeTroco.Models.Saldo", null)
                        .WithMany("Moeda")
                        .HasForeignKey("SaldoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MaquinaDeTroco.Models.Saldo", b =>
                {
                    b.HasOne("MaquinaDeTroco.Models.Caixa", "Caixa")
                        .WithMany()
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MaquinaDeTroco.Models.Sangria", b =>
                {
                    b.HasOne("MaquinaDeTroco.Models.Caixa", "Caixa")
                        .WithMany()
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaquinaDeTroco.Models.Moeda", "Moeda")
                        .WithMany()
                        .HasForeignKey("MoedaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaquinaDeTroco.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
